---
title: "Burden of Autoimmune Disease"
author: "MichaelAngelo Confiado"
date: "2022-11-19"
output: html_document
desciption: "3 questions: 1. Is there a difference in quality of life (QoL) between men and women with AI?
                          2. Does AI QoL generally improve over time? (Measured from time of onset)
                          3. Which age group has the highest burden of therapy? Is it significant?"
---

## PROJECT DESCRIPTION

```{r setup, include = FALSE}
knitr::opts_chunk$set(include = TRUE, echo = FALSE, warning = FALSE, message = FALSE)
```

```{r working directory, include = FALSE}

getwd()
setwd(getwd())

getwd()

```

```{r packages, include = FALSE}
library(rlang, quietly = TRUE)
library(readr, quietly = TRUE)
library(readxl, quietly = TRUE)
library(dplyr, quietly = TRUE)
library(tidyr, quietly = TRUE)
library(ggplot2, quietly = TRUE)
library(RColorBrewer, quietly = TRUE)
```

## DATASET DESCRIPTION
##### CITATION

```{r load excel, include = FALSE}
AIdata_raw <- read_xlsx("2_Data_AI-patients.xlsx", sheet = 1)
head(AIdata_raw)
str(AIdata_raw)
summary(AIdata_raw)
```

```{r cleaning, include = FALSE}

AIdata_clean <- AIdata_raw %>% 
                  mutate(Gender = as.factor(ifelse(Gender == 2, 0, 1)), #change to standard coding (M = 0, F = 1)
                         Recruitment = as.factor(Recruitment), #change to categorical
                         Education = as.factor(Education), #change to categorical
                         `Marital status` = as.factor(`Marital status`)) %>% #change to categorical
                  mutate(Gender = factor(Gender, labels = c("Male", "Female"))) %>%
                  na_if(-9) #replace -9 w/ NA
summary(AIdata_clean$Gender)

```


## PRELIM DA

```{r functions}
#function to generate histogram
plot_hist_dens <- function(column, factor = NULL, binwidth = 30){
  ggplot(AIdata_clean, aes(x = {{column}})) +
    geom_histogram(aes(y = ..count.., fill = {{factor}}),
                   alpha= 0.40,
                   binwidth = binwidth) +
    geom_density(aes(y = binwidth * ..count.., color = {{factor}}))
}

#function to generate bar plot
plot_bar <- function(column, fill = NULL, position = "identity"){
  ggplot(AIdata_clean, ) +
    geom_bar(aes({{column}}, fill = {{fill}}),
             position = position, 
             alpha = 0.75)
}

```

```{r exploratory}

ggplot(AIdata_clean, aes(x = Age)) +
  geom_histogram(aes(y = ..count.., fill = Gender),
                   position = "identity", 
                   alpha = 0.5,
                   binwidth = 5) +
  geom_density(aes(y = 5 * ..count.., color = Gender),
               alpha = 1.2) +
  facet_wrap(~Gender) +
  labs(title = "Age Distribution by Gender", x = "Age", y = "Count") +
  scale_fill_brewer(palette = "Accent") +
  scale_color_brewer(palette = "Accent")

plot_hist_dens(Age, Gender, 5) +
  facet_wrap(~Gender) +
  labs(title = "Age Distribution by Gender", x = "Age", y = "Count") +
  scale_fill_brewer(palette = "Accent") +
  scale_color_brewer(palette = "Accent")

plot_bar(`AI (number)`, Gender) +
  geom_density(aes(`AI (number)`)) +
  facet_wrap(~Gender)

plot_hist_dens(`Burden of symptoms`, Gender, 10) +
  facet_wrap(~Gender)

ggplot(AIdata_clean, aes(x = Gender, y = `Burden of symptoms`, fill=Gender)) +
  geom_boxplot(alpha = 0.5)

plot_hist_dens(`Burden of therapies`, Gender, 10) +
  facet_wrap(~Gender)

plot_hist_dens(`EQ-Index score`, Gender, 0.1) +
  facet_wrap(~Gender)

plot_hist_dens(`EQ-VAS score`, Gender, 10) +
  facet_wrap(~Gender)

```










